[package]
name = "ariax-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ariax-core.workspace = true
ariax-runtime.workspace = true
ariax-storage.workspace = true

[target.'cfg(windows)'.dev-dependencies]
ariax-windows-security.workspace = true

[lints]
workspace = true
