//! Bounded cookie storage with pinned public-suffix and owned SameSite policy.

use cookie::SameSite;
use cookie_store::{Cookie, CookieDomain, CookieExpiration, CookieStore};
use hyper::Method;
use hyper::header::HeaderValue;
use publicsuffix::{List, Psl};
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use std::error::Error;
use std::fmt;
#[cfg(unix)]
use std::fs::OpenOptions;
use std::fs::{self, File};
use std::io::{Read, Write};
use std::net::IpAddr;
use std::path::{Path, PathBuf};
use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};
use std::time::SystemTime;
use url::Url;

pub const DEFAULT_HTTP_COOKIE_TOTAL_ENTRIES: usize = 3000;
pub const MAX_HTTP_COOKIE_ENTRIES_PER_DOMAIN: usize = 180;
pub const MAX_HTTP_COOKIE_BYTES_PER_DOMAIN: usize = 64 * 1024;
pub const MAX_HTTP_COOKIE_BYTES: usize = 4096;
pub const MAX_HTTP_COOKIE_HEADER_BYTES: usize = 16 * 1024;
pub const MAX_HTTP_PSL_BYTES: usize = 4 * 1024 * 1024;
pub const MAX_HTTP_PSL_SNAPSHOT_ID_BYTES: usize = 128;
pub const MAX_HTTP_COOKIE_FILE_BYTES: usize = 8 * 1024 * 1024;
pub const MAX_HTTP_COOKIE_FILE_LINES: usize = 16 * 1024;
pub const HTTP_PSL_SNAPSHOT_ID: &str = "mozilla-psl-2026-07-25-e1b8015c";
pub const HTTP_PSL_SHA256: [u8; 32] = [
    0x08, 0x4a, 0x56, 0x74, 0xd7, 0x7c, 0x1d, 0x14, 0x90, 0x0b, 0x16, 0xda, 0x5f, 0xc8, 0xaf, 0xee,
    0x97, 0x65, 0xaf, 0x2f, 0x00, 0xa6, 0x38, 0x55, 0x2a, 0x8c, 0x7a, 0xa1, 0x8f, 0x44, 0xae, 0x81,
];

const BUNDLED_HTTP_PSL: &[u8] = include_bytes!("../../../assets/public-suffix-list.dat");
const NETSCAPE_COOKIE_HEADER: &str = "# Netscape HTTP Cookie File\n# This file was generated by ariax. Do not edit while ariax is running.\n";
const HTTP_ONLY_PREFIX: &str = "#HttpOnly_";
static COOKIE_TEMP_ID: AtomicU64 = AtomicU64::new(1);

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct HttpCookieLimits {
    pub total_entries: usize,
    pub entries_per_domain: usize,
    pub bytes_per_domain: usize,
    pub cookie_bytes: usize,
    pub header_bytes: usize,
}

impl Default for HttpCookieLimits {
    fn default() -> Self {
        Self {
            total_entries: DEFAULT_HTTP_COOKIE_TOTAL_ENTRIES,
            entries_per_domain: MAX_HTTP_COOKIE_ENTRIES_PER_DOMAIN,
            bytes_per_domain: MAX_HTTP_COOKIE_BYTES_PER_DOMAIN,
            cookie_bytes: MAX_HTTP_COOKIE_BYTES,
            header_bytes: MAX_HTTP_COOKIE_HEADER_BYTES,
        }
    }
}

impl HttpCookieLimits {
    fn validate(self) -> Result<Self, HttpCookieError> {
        if self.total_entries == 0
            || self.total_entries > DEFAULT_HTTP_COOKIE_TOTAL_ENTRIES
            || self.entries_per_domain == 0
            || self.entries_per_domain > MAX_HTTP_COOKIE_ENTRIES_PER_DOMAIN
            || self.bytes_per_domain == 0
            || self.bytes_per_domain > MAX_HTTP_COOKIE_BYTES_PER_DOMAIN
            || self.cookie_bytes == 0
            || self.cookie_bytes > MAX_HTTP_COOKIE_BYTES
            || self.header_bytes == 0
            || self.header_bytes > MAX_HTTP_COOKIE_HEADER_BYTES
        {
            return Err(HttpCookieError::InvalidLimits);
        }
        Ok(self)
    }
}

#[derive(Clone, Debug, Eq, PartialEq, Ord, PartialOrd)]
struct CookieKey {
    domain: Arc<str>,
    path: Arc<str>,
    name: Arc<str>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
struct CookieMetadata {
    bytes: usize,
    domain_bucket: Arc<str>,
    last_used: u64,
}

#[derive(Clone, Eq, PartialEq)]
pub struct HttpCookieHeader(HeaderValue);

impl HttpCookieHeader {
    #[must_use]
    pub const fn as_header_value(&self) -> &HeaderValue {
        &self.0
    }
}

impl fmt::Debug for HttpCookieHeader {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str("HttpCookieHeader(<redacted>)")
    }
}

#[derive(Clone)]
pub struct HttpCookieJar {
    store: CookieStore,
    suffixes: List,
    limits: HttpCookieLimits,
    metadata: BTreeMap<CookieKey, CookieMetadata>,
    sequence: u64,
    snapshot_id: Arc<str>,
    snapshot_sha256: [u8; 32],
}

impl fmt::Debug for HttpCookieJar {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter
            .debug_struct("HttpCookieJar")
            .field("entries", &self.metadata.len())
            .field("snapshot_id", &self.snapshot_id)
            .field("snapshot_sha256", &self.snapshot_sha256)
            .finish_non_exhaustive()
    }
}

impl HttpCookieJar {
    pub fn bundled(limits: HttpCookieLimits) -> Result<Self, HttpCookieError> {
        Self::new(
            BUNDLED_HTTP_PSL,
            HTTP_PSL_SNAPSHOT_ID.to_owned(),
            HTTP_PSL_SHA256,
            limits,
        )
    }

    pub fn new(
        public_suffix_list: &[u8],
        snapshot_id: String,
        expected_sha256: [u8; 32],
        limits: HttpCookieLimits,
    ) -> Result<Self, HttpCookieError> {
        let limits = limits.validate()?;
        if public_suffix_list.is_empty() || public_suffix_list.len() > MAX_HTTP_PSL_BYTES {
            return Err(HttpCookieError::InvalidPublicSuffixList);
        }
        if snapshot_id.is_empty()
            || snapshot_id.len() > MAX_HTTP_PSL_SNAPSHOT_ID_BYTES
            || !snapshot_id.is_ascii()
            || snapshot_id.bytes().any(|byte| byte.is_ascii_control())
        {
            return Err(HttpCookieError::InvalidSnapshotId);
        }
        let actual: [u8; 32] = Sha256::digest(public_suffix_list).into();
        if actual != expected_sha256 {
            return Err(HttpCookieError::PublicSuffixHashMismatch);
        }
        let suffixes = List::from_bytes(public_suffix_list)
            .map_err(|_| HttpCookieError::InvalidPublicSuffixList)?;
        let store = CookieStore::default().with_suffix_list(suffixes.clone());
        Ok(Self {
            store,
            suffixes,
            limits,
            metadata: BTreeMap::new(),
            sequence: 0,
            snapshot_id: snapshot_id.into(),
            snapshot_sha256: actual,
        })
    }

    pub fn store_set_cookie(
        &mut self,
        request_uri: &str,
        set_cookie: &str,
    ) -> Result<(), HttpCookieError> {
        if set_cookie.is_empty() || set_cookie.len() > self.limits.cookie_bytes {
            return Err(HttpCookieError::CookieTooLarge);
        }
        let request = parse_http_url(request_uri)?;
        let raw = cookie::Cookie::parse(set_cookie.to_owned())
            .map_err(|_| HttpCookieError::InvalidSetCookie)?
            .into_owned();
        self.store_raw_cookie(&request, raw)
    }

    fn store_raw_cookie(
        &mut self,
        request: &Url,
        raw: cookie::Cookie<'static>,
    ) -> Result<(), HttpCookieError> {
        if raw.same_site() == Some(SameSite::None) && raw.secure() != Some(true) {
            return Err(HttpCookieError::InsecureSameSiteNone);
        }
        let parsed = Cookie::try_from_raw_cookie(&raw, request)
            .map_err(|_| HttpCookieError::InvalidSetCookie)?
            .into_owned();
        let target_key = cookie_key(&parsed)?;
        let mut next_store = self.store.clone();
        next_store
            .insert(parsed, request)
            .map_err(|error| match error {
                cookie_store::CookieError::PublicSuffix => HttpCookieError::PublicSuffix,
                _ => HttpCookieError::InvalidSetCookie,
            })?;
        self.sequence = self.sequence.saturating_add(1);
        let mut metadata = rebuild_metadata(
            &next_store,
            &self.suffixes,
            &self.metadata,
            self.sequence,
            Some(&target_key),
        )?;
        enforce_cookie_limits(&mut next_store, &mut metadata, self.limits)?;
        self.store = next_store;
        self.metadata = metadata;
        Ok(())
    }

    /// Transactionally imports the bounded Netscape/aria2 cookie-file format.
    /// Existing cookies remain unchanged if any admitted line is malformed.
    pub fn load_netscape(&mut self, path: &Path) -> Result<usize, HttpCookieError> {
        let file = open_private_cookie_file(path)?;
        let metadata = file.metadata().map_err(|_| HttpCookieError::CookieFileIo)?;
        if !metadata.is_file() {
            return Err(HttpCookieError::CookieFileNotRegular);
        }
        if metadata.len() > MAX_HTTP_COOKIE_FILE_BYTES as u64 {
            return Err(HttpCookieError::CookieFileTooLarge);
        }
        let mut bytes = Vec::new();
        bytes
            .try_reserve_exact(
                usize::try_from(metadata.len()).map_err(|_| HttpCookieError::CookieFileTooLarge)?,
            )
            .map_err(|_| HttpCookieError::ResourceLimit)?;
        file.take((MAX_HTTP_COOKIE_FILE_BYTES + 1) as u64)
            .read_to_end(&mut bytes)
            .map_err(|_| HttpCookieError::CookieFileIo)?;
        if bytes.len() > MAX_HTTP_COOKIE_FILE_BYTES {
            return Err(HttpCookieError::CookieFileTooLarge);
        }
        let text = std::str::from_utf8(&bytes).map_err(|_| HttpCookieError::CookieFileSyntax)?;
        self.load_netscape_text(text)
    }

    pub fn load_netscape_text(&mut self, input: &str) -> Result<usize, HttpCookieError> {
        if input.len() > MAX_HTTP_COOKIE_FILE_BYTES {
            return Err(HttpCookieError::CookieFileTooLarge);
        }
        let mut next = self.clone();
        let mut imported = 0_usize;
        for (line_index, raw_line) in input.lines().enumerate() {
            if line_index >= MAX_HTTP_COOKIE_FILE_LINES {
                return Err(HttpCookieError::CookieFileTooManyLines);
            }
            let line = raw_line.strip_suffix('\r').unwrap_or(raw_line);
            if line.is_empty() || (line.starts_with('#') && !line.starts_with(HTTP_ONLY_PREFIX)) {
                continue;
            }
            let Some(record) = parse_netscape_cookie_line(line)? else {
                continue;
            };
            next.store_raw_cookie(&record.request, record.cookie)?;
            imported = imported
                .checked_add(1)
                .ok_or(HttpCookieError::ResourceLimit)?;
        }
        *self = next;
        Ok(imported)
    }

    /// Atomically writes persistent cookies only. Session cookies are never
    /// serialized to disk, and the destination directory must already be
    /// private to the current user.
    pub fn save_netscape(&self, path: &Path) -> Result<usize, HttpCookieError> {
        let (output, count) = self.netscape_bytes()?;
        let parent = path
            .parent()
            .filter(|parent| !parent.as_os_str().is_empty())
            .ok_or(HttpCookieError::CookieFilePath)?;
        verify_private_cookie_directory(parent)?;
        verify_replaceable_cookie_target(path)?;
        let temporary = cookie_temporary_path(path)?;
        let result = (|| {
            let mut file = create_private_cookie_file(&temporary)?;
            file.write_all(&output)
                .map_err(|_| HttpCookieError::CookieFileIo)?;
            file.flush().map_err(|_| HttpCookieError::CookieFileIo)?;
            file.sync_all().map_err(|_| HttpCookieError::CookieFileIo)?;
            drop(file);
            fs::rename(&temporary, path).map_err(|_| HttpCookieError::CookieFileIo)?;
            sync_cookie_parent(parent)?;
            Ok(count)
        })();
        if result.is_err() {
            let _ = fs::remove_file(&temporary);
        }
        result
    }

    fn netscape_bytes(&self) -> Result<(Vec<u8>, usize), HttpCookieError> {
        let mut output = Vec::from(NETSCAPE_COOKIE_HEADER.as_bytes());
        let mut count = 0_usize;
        for cookie in self.store.iter_unexpired() {
            let expires = match &cookie.expires {
                CookieExpiration::AtUtc(value) => value.unix_timestamp(),
                CookieExpiration::SessionEnd => continue,
            };
            if expires <= 0 {
                continue;
            }
            let (domain, include_subdomains) = match &cookie.domain {
                CookieDomain::HostOnly(domain) => (domain.as_str().to_owned(), false),
                CookieDomain::Suffix(domain) => (format!(".{domain}"), true),
                CookieDomain::Empty | CookieDomain::NotPresent => {
                    return Err(HttpCookieError::CookieFileSyntax);
                }
            };
            let path = String::from(&cookie.path);
            let name = cookie.name();
            let value = cookie.value();
            if !netscape_field_is_safe(&domain)
                || !netscape_field_is_safe(&path)
                || !valid_cookie_name(name)
                || !valid_cookie_value(value)
            {
                return Err(HttpCookieError::CookieFileSyntax);
            }
            if cookie.http_only() == Some(true) {
                output.extend_from_slice(HTTP_ONLY_PREFIX.as_bytes());
            }
            let line = format!(
                "{}\t{}\t{}\t{}\t{}\t{}\t{}\n",
                domain,
                if include_subdomains { "TRUE" } else { "FALSE" },
                path,
                if cookie.secure() == Some(true) {
                    "TRUE"
                } else {
                    "FALSE"
                },
                expires,
                name,
                value,
            );
            if output
                .len()
                .checked_add(line.len())
                .is_none_or(|length| length > MAX_HTTP_COOKIE_FILE_BYTES)
            {
                return Err(HttpCookieError::CookieFileTooLarge);
            }
            output.extend_from_slice(line.as_bytes());
            count = count.checked_add(1).ok_or(HttpCookieError::ResourceLimit)?;
        }
        Ok((output, count))
    }

    pub fn header_for(
        &mut self,
        request_uri: &str,
        top_level_uri: &str,
        method: &Method,
    ) -> Result<Option<HttpCookieHeader>, HttpCookieError> {
        let request = parse_http_url(request_uri)?;
        let top_level = parse_http_url(top_level_uri)?;
        let same_site =
            schemeful_site(&request, &self.suffixes) == schemeful_site(&top_level, &self.suffixes);
        let top_level_safe = matches!(*method, Method::GET | Method::HEAD);
        let mut selected = Vec::new();
        let mut selected_keys = Vec::new();
        let mut header_bytes = 0_usize;
        for cookie in self.store.matches(&request) {
            if !same_site_cookie_allowed(cookie, same_site, top_level_safe, &request) {
                continue;
            }
            let pair_bytes = cookie.name().len() + 1 + cookie.value().len();
            header_bytes = header_bytes
                .checked_add(pair_bytes + usize::from(!selected.is_empty()) * 2)
                .ok_or(HttpCookieError::HeaderTooLarge)?;
            if header_bytes > self.limits.header_bytes {
                return Err(HttpCookieError::HeaderTooLarge);
            }
            selected.push(format!("{}={}", cookie.name(), cookie.value()));
            selected_keys.push(cookie_key(cookie)?);
        }
        if selected.is_empty() {
            return Ok(None);
        }
        self.sequence = self.sequence.saturating_add(1);
        for key in selected_keys {
            if let Some(metadata) = self.metadata.get_mut(&key) {
                metadata.last_used = self.sequence;
            }
        }
        let value = HeaderValue::from_str(&selected.join("; "))
            .map_err(|_| HttpCookieError::InvalidSetCookie)?;
        Ok(Some(HttpCookieHeader(value)))
    }

    #[must_use]
    pub fn len(&self) -> usize {
        self.metadata.len()
    }

    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.metadata.is_empty()
    }

    #[must_use]
    pub fn snapshot_id(&self) -> &str {
        &self.snapshot_id
    }

    #[must_use]
    pub const fn snapshot_sha256(&self) -> &[u8; 32] {
        &self.snapshot_sha256
    }
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum HttpCookieError {
    InvalidLimits,
    InvalidSnapshotId,
    InvalidPublicSuffixList,
    PublicSuffixHashMismatch,
    InvalidUri,
    CookieTooLarge,
    InvalidSetCookie,
    InsecureSameSiteNone,
    PublicSuffix,
    HeaderTooLarge,
    ResourceLimit,
    CookieFileIo,
    CookieFileNotRegular,
    CookieFileInsecurePermissions,
    CookieFileTooLarge,
    CookieFileTooManyLines,
    CookieFileSyntax,
    CookieFilePath,
}

impl HttpCookieError {
    #[must_use]
    pub const fn code(self) -> &'static str {
        match self {
            Self::InvalidLimits => "invalid_cookie_limits",
            Self::InvalidSnapshotId => "invalid_psl_snapshot_id",
            Self::InvalidPublicSuffixList => "invalid_public_suffix_list",
            Self::PublicSuffixHashMismatch => "public_suffix_hash_mismatch",
            Self::InvalidUri => "invalid_cookie_uri",
            Self::CookieTooLarge => "cookie_too_large",
            Self::InvalidSetCookie => "invalid_set_cookie",
            Self::InsecureSameSiteNone => "insecure_samesite_none",
            Self::PublicSuffix => "cookie_public_suffix",
            Self::HeaderTooLarge => "cookie_header_too_large",
            Self::ResourceLimit => "cookie_resource_limit",
            Self::CookieFileIo => "cookie_file_io",
            Self::CookieFileNotRegular => "cookie_file_not_regular",
            Self::CookieFileInsecurePermissions => "cookie_file_insecure_permissions",
            Self::CookieFileTooLarge => "cookie_file_too_large",
            Self::CookieFileTooManyLines => "cookie_file_too_many_lines",
            Self::CookieFileSyntax => "cookie_file_syntax",
            Self::CookieFilePath => "cookie_file_path",
        }
    }
}

impl fmt::Display for HttpCookieError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(self.code())
    }
}

impl Error for HttpCookieError {}

struct NetscapeCookieRecord {
    request: Url,
    cookie: cookie::Cookie<'static>,
}

fn parse_netscape_cookie_line(line: &str) -> Result<Option<NetscapeCookieRecord>, HttpCookieError> {
    if line.len() > MAX_HTTP_COOKIE_BYTES * 3 {
        return Err(HttpCookieError::CookieFileSyntax);
    }
    let (http_only, line) = line
        .strip_prefix(HTTP_ONLY_PREFIX)
        .map_or((false, line), |line| (true, line));
    let fields = line.split('\t').collect::<Vec<_>>();
    let [
        domain,
        include_subdomains,
        path,
        secure,
        expires,
        name,
        value,
    ] = fields.as_slice()
    else {
        return Err(HttpCookieError::CookieFileSyntax);
    };
    if domain.is_empty()
        || !netscape_field_is_safe(domain)
        || !path.starts_with('/')
        || !netscape_field_is_safe(path)
        || !valid_cookie_name(name)
        || !valid_cookie_value(value)
    {
        return Err(HttpCookieError::CookieFileSyntax);
    }
    let include_subdomains = parse_netscape_bool(include_subdomains)?;
    let secure = parse_netscape_bool(secure)?;
    let expires = expires
        .parse::<u64>()
        .map_err(|_| HttpCookieError::CookieFileSyntax)?;
    if expires != 0
        && expires
            <= SystemTime::now()
                .duration_since(SystemTime::UNIX_EPOCH)
                .map_err(|_| HttpCookieError::CookieFileSyntax)?
                .as_secs()
    {
        return Ok(None);
    }
    let host = domain.trim_start_matches('.');
    if host.is_empty() {
        return Err(HttpCookieError::CookieFileSyntax);
    }
    let authority = if host.parse::<std::net::Ipv6Addr>().is_ok() {
        format!("[{host}]")
    } else {
        host.to_owned()
    };
    let scheme = if secure { "https" } else { "http" };
    let request = Url::parse(&format!("{scheme}://{authority}/"))
        .map_err(|_| HttpCookieError::CookieFileSyntax)?;
    if request.host_str().is_none_or(str::is_empty) {
        return Err(HttpCookieError::CookieFileSyntax);
    }

    let mut cookie = cookie::Cookie::new((*name).to_owned(), (*value).to_owned());
    cookie.set_path((*path).to_owned());
    cookie.set_secure(secure);
    cookie.set_http_only(http_only);
    if include_subdomains {
        cookie.set_domain(host.to_owned());
    }
    if expires != 0 {
        let timestamp = i64::try_from(expires).map_err(|_| HttpCookieError::CookieFileSyntax)?;
        let expiration = cookie::time::OffsetDateTime::from_unix_timestamp(timestamp)
            .map_err(|_| HttpCookieError::CookieFileSyntax)?;
        cookie.set_expires(expiration);
    }
    Ok(Some(NetscapeCookieRecord { request, cookie }))
}

fn parse_netscape_bool(value: &str) -> Result<bool, HttpCookieError> {
    match value {
        "TRUE" => Ok(true),
        "FALSE" => Ok(false),
        _ => Err(HttpCookieError::CookieFileSyntax),
    }
}

fn valid_cookie_name(value: &str) -> bool {
    !value.is_empty()
        && value.len() <= MAX_HTTP_COOKIE_BYTES
        && value.bytes().all(|byte| {
            byte.is_ascii_alphanumeric()
                || matches!(
                    byte,
                    b'!' | b'#'
                        | b'$'
                        | b'%'
                        | b'&'
                        | b'\''
                        | b'*'
                        | b'+'
                        | b'-'
                        | b'.'
                        | b'^'
                        | b'_'
                        | b'`'
                        | b'|'
                        | b'~'
                )
        })
}

fn valid_cookie_value(value: &str) -> bool {
    value.len() <= MAX_HTTP_COOKIE_BYTES
        && value.bytes().all(|byte| {
            !byte.is_ascii_control() && !matches!(byte, b' ' | b'"' | b',' | b';' | b'\\' | b'\t')
        })
}

fn netscape_field_is_safe(value: &str) -> bool {
    value.len() <= MAX_HTTP_COOKIE_BYTES
        && !value.is_empty()
        && !value
            .bytes()
            .any(|byte| byte == b'\t' || byte == b'\r' || byte == b'\n' || byte == 0)
}

#[cfg(unix)]
fn open_private_cookie_file(path: &Path) -> Result<File, HttpCookieError> {
    use rustix::fs::{Mode, OFlags, open};
    use std::os::unix::fs::{MetadataExt as _, PermissionsExt as _};

    let fd = open(
        path,
        OFlags::RDONLY | OFlags::CLOEXEC | OFlags::NOFOLLOW,
        Mode::empty(),
    )
    .map_err(|_| HttpCookieError::CookieFileIo)?;
    let file = File::from(fd);
    let metadata = file.metadata().map_err(|_| HttpCookieError::CookieFileIo)?;
    if !metadata.is_file() {
        return Err(HttpCookieError::CookieFileNotRegular);
    }
    if metadata.permissions().mode() & 0o077 != 0 || metadata.nlink() != 1 {
        return Err(HttpCookieError::CookieFileInsecurePermissions);
    }
    Ok(file)
}

#[cfg(windows)]
fn open_private_cookie_file(path: &Path) -> Result<File, HttpCookieError> {
    ariax_windows_security::verify_private_file(path)
        .and_then(|()| ariax_windows_security::verify_single_link_regular_file(path))
        .map_err(|_| HttpCookieError::CookieFileInsecurePermissions)?;
    File::open(path).map_err(|_| HttpCookieError::CookieFileIo)
}

#[cfg(not(any(unix, windows)))]
fn open_private_cookie_file(_path: &Path) -> Result<File, HttpCookieError> {
    Err(HttpCookieError::CookieFileInsecurePermissions)
}

#[cfg(unix)]
fn verify_private_cookie_directory(path: &Path) -> Result<(), HttpCookieError> {
    use std::os::unix::fs::PermissionsExt as _;

    let metadata = fs::symlink_metadata(path).map_err(|_| HttpCookieError::CookieFileIo)?;
    if metadata.file_type().is_symlink() || !metadata.is_dir() {
        return Err(HttpCookieError::CookieFilePath);
    }
    if metadata.permissions().mode() & 0o077 != 0 {
        return Err(HttpCookieError::CookieFileInsecurePermissions);
    }
    Ok(())
}

#[cfg(windows)]
fn verify_private_cookie_directory(path: &Path) -> Result<(), HttpCookieError> {
    ariax_windows_security::verify_private_directory(path)
        .map_err(|_| HttpCookieError::CookieFileInsecurePermissions)
}

#[cfg(not(any(unix, windows)))]
fn verify_private_cookie_directory(_path: &Path) -> Result<(), HttpCookieError> {
    Err(HttpCookieError::CookieFileInsecurePermissions)
}

fn verify_replaceable_cookie_target(path: &Path) -> Result<(), HttpCookieError> {
    match fs::symlink_metadata(path) {
        Ok(metadata) => {
            if metadata.file_type().is_symlink() || !metadata.is_file() {
                return Err(HttpCookieError::CookieFileNotRegular);
            }
            verify_private_cookie_target(path, &metadata)
        }
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => Ok(()),
        Err(_) => Err(HttpCookieError::CookieFileIo),
    }
}

#[cfg(unix)]
fn verify_private_cookie_target(
    _path: &Path,
    metadata: &fs::Metadata,
) -> Result<(), HttpCookieError> {
    use std::os::unix::fs::{MetadataExt as _, PermissionsExt as _};

    if metadata.permissions().mode() & 0o077 != 0 || metadata.nlink() != 1 {
        return Err(HttpCookieError::CookieFileInsecurePermissions);
    }
    Ok(())
}

#[cfg(windows)]
fn verify_private_cookie_target(
    path: &Path,
    _metadata: &fs::Metadata,
) -> Result<(), HttpCookieError> {
    ariax_windows_security::verify_private_file(path)
        .and_then(|()| ariax_windows_security::verify_single_link_regular_file(path))
        .map_err(|_| HttpCookieError::CookieFileInsecurePermissions)
}

#[cfg(not(any(unix, windows)))]
fn verify_private_cookie_target(
    _path: &Path,
    _metadata: &fs::Metadata,
) -> Result<(), HttpCookieError> {
    Err(HttpCookieError::CookieFileInsecurePermissions)
}

fn cookie_temporary_path(path: &Path) -> Result<PathBuf, HttpCookieError> {
    let parent = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .ok_or(HttpCookieError::CookieFilePath)?;
    let id = COOKIE_TEMP_ID.fetch_add(1, Ordering::Relaxed);
    Ok(parent.join(format!(".ariax-cookie-{}-{id}.tmp", std::process::id())))
}

#[cfg(unix)]
fn create_private_cookie_file(path: &Path) -> Result<File, HttpCookieError> {
    use std::os::unix::fs::OpenOptionsExt as _;

    OpenOptions::new()
        .write(true)
        .create_new(true)
        .mode(0o600)
        .open(path)
        .map_err(|_| HttpCookieError::CookieFileIo)
}

#[cfg(windows)]
fn create_private_cookie_file(path: &Path) -> Result<File, HttpCookieError> {
    ariax_windows_security::create_private_file(path).map_err(|_| HttpCookieError::CookieFileIo)
}

#[cfg(not(any(unix, windows)))]
fn create_private_cookie_file(_path: &Path) -> Result<File, HttpCookieError> {
    Err(HttpCookieError::CookieFileInsecurePermissions)
}

#[cfg(unix)]
fn sync_cookie_parent(path: &Path) -> Result<(), HttpCookieError> {
    File::open(path)
        .and_then(|directory| directory.sync_all())
        .map_err(|_| HttpCookieError::CookieFileIo)
}

#[cfg(not(unix))]
fn sync_cookie_parent(_path: &Path) -> Result<(), HttpCookieError> {
    Ok(())
}

fn parse_http_url(input: &str) -> Result<Url, HttpCookieError> {
    let url = Url::parse(input).map_err(|_| HttpCookieError::InvalidUri)?;
    if !matches!(url.scheme(), "http" | "https")
        || url.host_str().is_none_or(str::is_empty)
        || !url.username().is_empty()
        || url.password().is_some()
    {
        return Err(HttpCookieError::InvalidUri);
    }
    Ok(url)
}

fn cookie_key(cookie: &Cookie<'_>) -> Result<CookieKey, HttpCookieError> {
    let domain = cookie
        .domain
        .as_cow()
        .ok_or(HttpCookieError::InvalidSetCookie)?;
    Ok(CookieKey {
        domain: domain.as_ref().to_owned().into(),
        path: String::from(&cookie.path).into(),
        name: cookie.name().to_owned().into(),
    })
}

fn rebuild_metadata(
    store: &CookieStore,
    suffixes: &List,
    previous: &BTreeMap<CookieKey, CookieMetadata>,
    sequence: u64,
    touched: Option<&CookieKey>,
) -> Result<BTreeMap<CookieKey, CookieMetadata>, HttpCookieError> {
    let mut output = BTreeMap::new();
    for cookie in store.iter_unexpired() {
        let key = cookie_key(cookie)?;
        let last_used = if touched == Some(&key) {
            sequence
        } else {
            previous.get(&key).map_or(sequence, |entry| entry.last_used)
        };
        let domain_bucket = registrable_domain(&key.domain, suffixes);
        output.insert(
            key,
            CookieMetadata {
                bytes: cookie.to_string().len(),
                domain_bucket: domain_bucket.into(),
                last_used,
            },
        );
    }
    Ok(output)
}

fn enforce_cookie_limits(
    store: &mut CookieStore,
    metadata: &mut BTreeMap<CookieKey, CookieMetadata>,
    limits: HttpCookieLimits,
) -> Result<(), HttpCookieError> {
    loop {
        let mut domains: BTreeMap<Arc<str>, (usize, usize)> = BTreeMap::new();
        for entry in metadata.values() {
            let aggregate = domains.entry(Arc::clone(&entry.domain_bucket)).or_default();
            aggregate.0 += 1;
            aggregate.1 = aggregate
                .1
                .checked_add(entry.bytes)
                .ok_or(HttpCookieError::ResourceLimit)?;
        }
        let overfull = domains.into_iter().find(|(_, (count, bytes))| {
            *count > limits.entries_per_domain || *bytes > limits.bytes_per_domain
        });
        let candidate = if let Some((domain, _)) = overfull {
            metadata
                .iter()
                .filter(|(_, entry)| entry.domain_bucket == domain)
                .min_by_key(|(_, entry)| entry.last_used)
                .map(|(key, _)| key.clone())
        } else if metadata.len() > limits.total_entries {
            metadata
                .iter()
                .min_by_key(|(_, entry)| entry.last_used)
                .map(|(key, _)| key.clone())
        } else {
            return Ok(());
        };
        let key = candidate.ok_or(HttpCookieError::ResourceLimit)?;
        store.remove(&key.domain, &key.path, &key.name);
        metadata.remove(&key);
    }
}

fn registrable_domain(host: &str, suffixes: &List) -> String {
    let canonical = host.trim_matches(['[', ']']);
    if canonical.parse::<IpAddr>().is_ok() {
        return host.to_owned();
    }
    suffixes
        .domain(canonical.as_bytes())
        .and_then(|domain| std::str::from_utf8(domain.as_bytes()).ok())
        .unwrap_or(canonical)
        .to_owned()
}

fn schemeful_site(url: &Url, suffixes: &List) -> (String, String) {
    let host = url.host_str().expect("validated URL has a host");
    (url.scheme().to_owned(), registrable_domain(host, suffixes))
}

fn same_site_cookie_allowed(
    cookie: &Cookie<'_>,
    same_site: bool,
    top_level_safe: bool,
    request: &Url,
) -> bool {
    match cookie.same_site() {
        Some(SameSite::Strict) => same_site,
        Some(SameSite::Lax) | None => same_site || top_level_safe,
        Some(SameSite::None) => cookie.secure() == Some(true) && request.scheme() == "https",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicU64, Ordering};

    const TEST_PSL: &[u8] = b"// ===BEGIN ICANN DOMAINS===\ncom\nco.uk\n// ===END ICANN DOMAINS===\n// ===BEGIN PRIVATE DOMAINS===\ngithub.io\n// ===END PRIVATE DOMAINS===\n";
    static TEST_DIRECTORY_ID: AtomicU64 = AtomicU64::new(1);

    struct TestDirectory(PathBuf);

    impl TestDirectory {
        fn new() -> Self {
            let path = std::env::temp_dir().join(format!(
                "ariax-http-cookie-{}-{}",
                std::process::id(),
                TEST_DIRECTORY_ID.fetch_add(1, Ordering::Relaxed)
            ));
            #[cfg(unix)]
            {
                use std::os::unix::fs::DirBuilderExt as _;
                let mut builder = fs::DirBuilder::new();
                builder.mode(0o700);
                builder.create(&path).expect("create private directory");
            }
            #[cfg(windows)]
            ariax_windows_security::create_private_directory(&path)
                .expect("create private directory");
            Self(path)
        }
    }

    impl Drop for TestDirectory {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn jar_with_limits(limits: HttpCookieLimits) -> HttpCookieJar {
        HttpCookieJar::new(
            TEST_PSL,
            "test-2026-08-11".to_owned(),
            Sha256::digest(TEST_PSL).into(),
            limits,
        )
        .expect("jar")
    }

    #[test]
    fn rejects_public_suffix_and_insecure_samesite_none_cookies() {
        let mut jar = jar_with_limits(HttpCookieLimits::default());
        assert_eq!(
            jar.store_set_cookie("https://site.example.com/", "wide=x; Domain=com; Path=/"),
            Err(HttpCookieError::PublicSuffix)
        );
        assert_eq!(
            jar.store_set_cookie("https://site.example.com/", "none=x; SameSite=None; Path=/"),
            Err(HttpCookieError::InsecureSameSiteNone)
        );
        assert_eq!(jar.len(), 0);
    }

    #[test]
    fn rederives_host_scoped_and_samesite_headers_for_each_hop() {
        let mut jar = jar_with_limits(HttpCookieLimits::default());
        jar.store_set_cookie(
            "https://a.example.com/start",
            "strict=one; Secure; SameSite=Strict; Path=/",
        )
        .expect("strict cookie");
        jar.store_set_cookie(
            "https://a.example.com/start",
            "lax=two; Secure; SameSite=Lax; Path=/",
        )
        .expect("lax cookie");
        jar.store_set_cookie(
            "https://a.example.com/start",
            "none=three; Secure; SameSite=None; Path=/",
        )
        .expect("none cookie");

        let same = jar
            .header_for(
                "https://a.example.com/next",
                "https://a.example.com/start",
                &Method::GET,
            )
            .expect("header")
            .expect("cookies")
            .as_header_value()
            .to_str()
            .expect("ASCII")
            .to_owned();
        assert!(same.contains("strict=one"));
        assert!(same.contains("lax=two"));
        assert!(same.contains("none=three"));

        let cross = jar
            .header_for(
                "https://a.example.com/next",
                "https://other.test/start",
                &Method::GET,
            )
            .expect("header")
            .expect("cookies")
            .as_header_value()
            .to_str()
            .expect("ASCII")
            .to_owned();
        assert!(!cross.contains("strict=one"));
        assert!(cross.contains("lax=two"));
        assert!(cross.contains("none=three"));
        assert!(
            jar.header_for(
                "https://unrelated.example.net/",
                "https://a.example.com/start",
                &Method::GET,
            )
            .expect("header")
            .is_none()
        );
    }

    #[test]
    fn enforces_per_domain_lru_and_redacts_cookie_header_debug() {
        let limits = HttpCookieLimits {
            total_entries: 3,
            entries_per_domain: 2,
            bytes_per_domain: 1024,
            cookie_bytes: 1024,
            header_bytes: 1024,
        };
        let mut jar = jar_with_limits(limits);
        jar.store_set_cookie("https://a.example.com/", "one=1; Path=/")
            .expect("one");
        jar.store_set_cookie("https://a.example.com/", "two=2; Path=/")
            .expect("two");
        jar.store_set_cookie("https://a.example.com/", "three=3; Path=/")
            .expect("three");
        assert_eq!(jar.len(), 2);
        let header = jar
            .header_for(
                "https://a.example.com/",
                "https://a.example.com/",
                &Method::GET,
            )
            .expect("header")
            .expect("cookies");
        let text = header.as_header_value().to_str().expect("ASCII");
        assert!(!text.contains("one=1"));
        assert!(text.contains("two=2"));
        assert!(text.contains("three=3"));
        assert!(!format!("{header:?}").contains("three=3"));
    }

    #[test]
    fn fails_closed_when_public_suffix_snapshot_hash_or_data_is_wrong() {
        assert!(matches!(
            HttpCookieJar::new(
                TEST_PSL,
                "test".to_owned(),
                [0; 32],
                HttpCookieLimits::default()
            ),
            Err(HttpCookieError::PublicSuffixHashMismatch)
        ));
        let invalid = b"not a valid list";
        assert!(matches!(
            HttpCookieJar::new(
                invalid,
                "test".to_owned(),
                Sha256::digest(invalid).into(),
                HttpCookieLimits::default()
            ),
            Err(HttpCookieError::InvalidPublicSuffixList)
        ));
    }

    #[test]
    fn bundled_public_suffix_snapshot_is_hash_pinned_and_active() {
        let mut jar = HttpCookieJar::bundled(HttpCookieLimits::default()).expect("bundled jar");
        assert_eq!(jar.snapshot_id(), HTTP_PSL_SNAPSHOT_ID);
        assert_eq!(jar.snapshot_sha256(), &HTTP_PSL_SHA256);
        assert_eq!(
            jar.store_set_cookie(
                "https://site.example.co.uk/",
                "wide=x; Domain=co.uk; Path=/"
            ),
            Err(HttpCookieError::PublicSuffix)
        );
    }

    #[test]
    fn netscape_import_is_transactional_and_save_omits_session_cookies() {
        let mut jar = jar_with_limits(HttpCookieLimits::default());
        let input = concat!(
            "# Netscape HTTP Cookie File\n",
            ".example.com\tTRUE\t/\tTRUE\t4102444800\tpersistent\tone\n",
            "#HttpOnly_example.com\tFALSE\t/\tFALSE\t4102444800\thost\ttwo\n",
            "example.com\tFALSE\t/\tFALSE\t0\tsession\tthree\n",
        );
        assert_eq!(jar.load_netscape_text(input).expect("import cookies"), 3);
        let before = jar
            .header_for("https://example.com/", "https://example.com/", &Method::GET)
            .expect("header")
            .expect("cookies")
            .as_header_value()
            .to_str()
            .expect("ASCII")
            .to_owned();
        assert!(before.contains("persistent=one"));
        assert!(before.contains("host=two"));
        assert!(before.contains("session=three"));

        let invalid = concat!(
            "example.com\tFALSE\t/\tFALSE\t4102444800\thost\treplaced\n",
            "malformed\n",
        );
        assert_eq!(
            jar.load_netscape_text(invalid),
            Err(HttpCookieError::CookieFileSyntax)
        );
        let after = jar
            .header_for("https://example.com/", "https://example.com/", &Method::GET)
            .expect("header")
            .expect("cookies")
            .as_header_value()
            .to_str()
            .expect("ASCII")
            .to_owned();
        assert!(after.contains("host=two"));
        assert!(!after.contains("host=replaced"));

        let directory = TestDirectory::new();
        let path = directory.0.join("cookies.txt");
        assert_eq!(jar.save_netscape(&path).expect("save cookies"), 2);
        let saved = fs::read_to_string(&path).expect("read saved cookies");
        assert!(saved.starts_with("# Netscape HTTP Cookie File\n"));
        assert!(saved.contains("#HttpOnly_example.com"));
        assert!(saved.contains("persistent\tone"));
        assert!(!saved.contains("session\tthree"));

        let mut restored = jar_with_limits(HttpCookieLimits::default());
        assert_eq!(restored.load_netscape(&path).expect("reload cookies"), 2);
        let restored = restored
            .header_for("https://example.com/", "https://example.com/", &Method::GET)
            .expect("header")
            .expect("cookies")
            .as_header_value()
            .to_str()
            .expect("ASCII")
            .to_owned();
        assert!(restored.contains("persistent=one"));
        assert!(restored.contains("host=two"));
        assert!(!restored.contains("session=three"));
    }

    #[cfg(unix)]
    #[test]
    fn cookie_files_reject_insecure_permissions_and_symlinks() {
        use std::os::unix::fs::{PermissionsExt as _, symlink};

        let directory = TestDirectory::new();
        let insecure = directory.0.join("insecure.txt");
        fs::write(
            &insecure,
            "example.com\tFALSE\t/\tFALSE\t4102444800\tname\tvalue\n",
        )
        .expect("write cookie file");
        fs::set_permissions(&insecure, fs::Permissions::from_mode(0o644))
            .expect("set insecure mode");
        let mut jar = jar_with_limits(HttpCookieLimits::default());
        assert_eq!(
            jar.load_netscape(&insecure),
            Err(HttpCookieError::CookieFileInsecurePermissions)
        );

        fs::set_permissions(&insecure, fs::Permissions::from_mode(0o600))
            .expect("set private mode");
        let link = directory.0.join("link.txt");
        symlink(&insecure, &link).expect("create symlink");
        assert!(jar.load_netscape(&link).is_err());

        fs::set_permissions(&directory.0, fs::Permissions::from_mode(0o755))
            .expect("make directory insecure");
        assert_eq!(
            jar.save_netscape(&directory.0.join("saved.txt")),
            Err(HttpCookieError::CookieFileInsecurePermissions)
        );
    }
}
